// One-shot Mongo → Supabase migration for the WalletPickle backfill.
// Reads collections in FK-safe order, maps Mongo ObjectIds to deterministic
// UUIDs, and inserts via the service_role Supabase client (bypasses RLS).
//
// User decisions locked in:
//   - Sole owner: sumeet@ratepickle.com. All posts get his UUID as author_id.
//   - Old team users (Divyanshu, Vyan, test) are NOT migrated. No auth accounts.
//   - trendingsnapshots + tickersnapshots are skipped (regenerated by cron).

import { MongoClient } from 'mongodb';
import { createClient } from '@supabase/supabase-js';

const OWNER_EMAIL = 'sumeet@ratepickle.com';

// ---------- clients ----------
const mongo = new MongoClient(process.env.MONGO_URI);
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  { auth: { persistSession: false } },
);

// ---------- helpers ----------
// Mongo ObjectId (24 hex chars) → deterministic UUID (32 hex chars).
// Preserves the ObjectId in the first 24 chars, pads with zeros.
function oidToUuid(id) {
  if (!id) return null;
  const hex = id.toString().padEnd(32, '0');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

// Ad placement enum: Mongo used hyphens, Postgres uses snake_case.
const PLACEMENT_MAP = {
  'homepage': 'homepage',
  'sidebar': 'sidebar',
  'in-article': 'in_article',
  'top-banner': 'top_banner',
  'section-divider': 'section_divider',
};

async function insertBatch(table, rows, chunk = 500) {
  if (rows.length === 0) {
    console.log(`  ${table}: (nothing to insert)`);
    return;
  }
  for (let i = 0; i < rows.length; i += chunk) {
    const batch = rows.slice(i, i + chunk);
    const { error } = await supabase.from(table).insert(batch);
    if (error) {
      console.error(`  ✗ ${table} batch ${i}-${i + batch.length}:`, error.message);
      throw error;
    }
  }
  console.log(`  ✓ ${table}: ${rows.length} rows`);
}

// ---------- main ----------
async function main() {
  await mongo.connect();
  const db = mongo.db();
  console.log(`\nMongo: ${db.databaseName}`);
  console.log(`Supabase: ${process.env.NEXT_PUBLIC_SUPABASE_URL}\n`);

  // Look up the sole owner's Supabase UUID by email.
  const { data: authList, error: authErr } = await supabase.auth.admin.listUsers();
  if (authErr) throw authErr;
  const owner = authList.users.find(u => u.email === OWNER_EMAIL);
  if (!owner) throw new Error(`Owner ${OWNER_EMAIL} not found in Supabase Auth`);
  console.log(`Owner UUID: ${owner.id}\n`);

  // -------------------- 1. verticals --------------------
  console.log('→ verticals');
  const mongoVerticals = await db.collection('verticals').find({}).toArray();
  const verticalRows = mongoVerticals.map(v => ({
    id: oidToUuid(v._id),
    name: v.name,
    slug: v.slug,
    active: v.active ?? true,
    featured: v.featured ?? false,
    featured_order: v.featuredOrder ?? 1,
    created_at: v.createdAt ?? new Date(),
    updated_at: v.updatedAt ?? new Date(),
  }));
  await insertBatch('verticals', verticalRows);

  // -------------------- 2. ads --------------------
  console.log('→ ads');
  const mongoAds = await db.collection('ads').find({}).toArray();
  const adRows = mongoAds.map(a => ({
    id: oidToUuid(a._id),
    name: a.name || `${a.type || 'ad'} — ${a.placement || 'unknown'}`,
    type: a.type,
    image: a.image ?? null,
    cta_text: a.ctaText ?? null,
    cta_url: a.ctaUrl ?? null,
    target_vertical_id: a.targetVertical ? oidToUuid(a.targetVertical) : null,
    placement: PLACEMENT_MAP[a.placement] || a.placement,
    active: a.active ?? true,
    start_date: a.startDate ?? null,
    end_date: a.endDate ?? null,
    created_at: a.createdAt ?? new Date(),
    updated_at: a.updatedAt ?? new Date(),
  }));
  await insertBatch('ads', adRows);

  // -------------------- 3. posts --------------------
  console.log('→ posts');
  const verticalIds = new Set(verticalRows.map(v => v.id));
  const adIds = new Set(adRows.map(a => a.id));
  const mongoPosts = await db.collection('posts').find({}).toArray();
  let skippedPosts = 0;
  const postRows = mongoPosts.flatMap(p => {
    const vid = oidToUuid(p.vertical);
    if (!verticalIds.has(vid)) {
      console.warn(`   skip post ${p._id} — vertical ${p.vertical} not found`);
      skippedPosts++;
      return [];
    }
    return [{
      id: oidToUuid(p._id),
      title: p.title,
      slug: p.slug,
      vertical_id: vid,
      excerpt: p.excerpt ?? null,
      banner_image: p.bannerImage ?? null,
      body: p.body ?? {},
      author_id: owner.id,  // sole owner
      status: p.status || 'draft',
      publish_date: p.publishDate ?? null,
      read_time: p.readTime ?? null,
      editors_pick: p.editorsPick ?? false,
      is_dummy_seed: p.isDummySeed ?? false,
      // Null out ad_slot refs pointing at ads that no longer exist.
      ad_slot_1_id: p.adSlot1 && adIds.has(oidToUuid(p.adSlot1)) ? oidToUuid(p.adSlot1) : null,
      ad_slot_2_id: p.adSlot2 && adIds.has(oidToUuid(p.adSlot2)) ? oidToUuid(p.adSlot2) : null,
      created_at: p.createdAt ?? new Date(),
      updated_at: p.updatedAt ?? new Date(),
    }];
  });
  if (skippedPosts) console.warn(`   (skipped ${skippedPosts} orphaned posts)`);
  await insertBatch('posts', postRows);
  const postIds = new Set(postRows.map(p => p.id));

  // -------------------- 4. subscribers --------------------
  console.log('→ subscribers');
  const mongoSubs = await db.collection('subscribers').find({}).toArray();
  const subRows = mongoSubs.map(s => ({
    id: oidToUuid(s._id),
    email: s.email,
    unsubscribe_token: s.unsubscribeToken ?? null,
    subscribed_at: s.subscribedAt ?? s.createdAt ?? new Date(),
    created_at: s.createdAt ?? new Date(),
    updated_at: s.updatedAt ?? new Date(),
  }));
  await insertBatch('subscribers', subRows);

  // -------------------- 5. petitions --------------------
  console.log('→ petitions');
  const mongoPetitions = await db.collection('petitions').find({}).toArray();
  const petitionRows = mongoPetitions.map(p => ({
    id: oidToUuid(p._id),
    title: p.title,
    category: p.category,
    signature_count: p.signatureCount ?? 0,
    goal_count: p.goalCount,
    active: p.active ?? true,
    created_at: p.createdAt ?? new Date(),
    updated_at: p.updatedAt ?? new Date(),
  }));
  await insertBatch('petitions', petitionRows);

  // -------------------- 6. petition_signatures --------------------
  console.log('→ petition_signatures');
  const petitionIds = new Set(petitionRows.map(p => p.id));
  const mongoSigs = await db.collection('petitionsignatures').find({}).toArray();
  let skippedSigs = 0;
  const sigRows = mongoSigs.flatMap(s => {
    const pid = oidToUuid(s.petition);
    if (!petitionIds.has(pid)) { skippedSigs++; return []; }
    return [{
      id: oidToUuid(s._id),
      petition_id: pid,
      email: (s.email || '').toLowerCase(),
      created_at: s.createdAt ?? new Date(),
    }];
  });
  if (skippedSigs) console.warn(`   (skipped ${skippedSigs} orphaned signatures)`);
  await insertBatch('petition_signatures', sigRows);

  // -------------------- 7. post_views --------------------
  console.log('→ post_views (2000+ rows, batching)');
  const mongoViews = await db.collection('postviews').find({}).toArray();
  let skippedViews = 0;
  const viewRows = mongoViews.flatMap(v => {
    const pid = oidToUuid(v.post);
    if (!postIds.has(pid)) { skippedViews++; return []; }
    return [{
      post_id: pid,
      timestamp: v.timestamp ?? v.createdAt ?? new Date(),
      ip_hash: v.ipHash ?? null,
      is_seeded: v.isSeeded ?? false,
      // Note: no `id` — post_views.id is bigserial, DB assigns it
    }];
  });
  if (skippedViews) console.warn(`   (skipped ${skippedViews} orphaned post_views)`);
  await insertBatch('post_views', viewRows);

  console.log('\n✓ Migration complete.\n');
}

try {
  await main();
} catch (err) {
  console.error('\n✗ Migration failed:', err);
  process.exit(1);
} finally {
  await mongo.close();
}
